apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-12-09T17:52:01Z"
  generation: 1
  labels:
    app: nginx-1
  name: nginx-1
  namespace: default
  resourceVersion: "837671"
  uid: 2e0049e2-d106-4bd4-af85-4830ab681dec
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-1
    spec:
      containers:
      - image: us-east1-docker.pkg.dev/osd-ccs-admin-406615/mansour/client@sha256:09448923bf2c37197543535863f308d08517b8a7ac01fcd9400f5858460760d9
        imagePullPolicy: IfNotPresent
        name: client-sha256-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2023-12-09T17:52:21Z"
    lastUpdateTime: "2023-12-09T17:52:21Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-12-09T17:52:02Z"
    lastUpdateTime: "2023-12-09T17:52:21Z"
    message: ReplicaSet "nginx-1-78574d964d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3